// Auto-generated from kampylos_gpu_types.h + kampylos_kernel.cl by
// embed_kampylos_cl.py -- do not hand-edit.
static const char kKampylosClTypesSource[] =
"#pragma once\n"
"// Plain data types shared between kampylos_gpu_kernel.cu (the CUDA kernel) and\n"
"// kampylos_gpu_complete.h (the host-side completion step that follows it) -- no CUDA keywords\n"
"// here, so a plain C++ compiler (building main_kampylos_boinc.cpp's eventual GPU wrapper, not\n"
"// nvcc) can include this and kampylos_gpu_complete.h without also needing to understand\n"
"// __global__/__device__. Only the kernel .cu file itself needs those.\n"
"\n"
"struct LightCurvePoint {\n"
"    double t;\n"
"    double flux;\n"
"    double sigma;\n"
"};\n"
"\n"
"// Matches fit_binary_local's x[] order (t0, u0, log_tE, alpha, log_rho) -- s and q are fixed for\n"
"// the whole grid cell (passed separately, not per-candidate) since every candidate in one kernel\n"
"// launch belongs to the same (log_s, log_q) cell.\n"
"struct Candidate {\n"
"    double t0;\n"
"    double u0;\n"
"    double log_tE;\n"
"    double alpha;\n"
"    double log_rho;\n"
"};\n"
"\n"
"// Fixed per-candidate capacity for bad-point indices. First set to 64 on the assumption that\n"
"// needing the finite-source fallback at all would be a rare, small-cluster occurrence; tests\n"
"// against a realistic light curve (tests/test_kampylos_gpu_kernel.cu, 1744 points, dense\n"
"// near-peak sampling) overflowed that on 532/2001 candidates -- not rare, and the real in-event\n"
"// cluster is wider than 64 points. Raised to 512, confirmed by the same test to clear every\n"
"// candidate with zero overflow (max observed: see that test's own printed max_bad). `overflow`\n"
"// stays as the safety valve for the genuinely pathological case beyond that -- the caller's\n"
"// choice how to handle it (e.g. fall back to this candidate's GPU-only sums as an approximation,\n"
"// or redo it entirely on the CPU, or raise this constant further), not something this file\n"
"// decides.\n"
"#define KAMPYLOS_MAX_BAD_POINTS 512\n"
"\n"
"struct CandidateResult {\n"
"    // Six sufficient statistics from the fast-path-OK points only -- the caller (see\n"
"    // kampylos_gpu_complete.h) completes these by adding each listed bad point's real\n"
"    // contribution, then derives fs, fb, chi2 in closed form (see kampylos_gpu_kernel.cu's top\n"
"    // comment for the identity). Not meaningful on their own when poisoned/overflow are set.\n"
"    double S_AA, S_A1, S_11, S_Ay, S_1y, S_yy;\n"
"    int n_bad;\n"
"    int overflow;             // 1 if more than KAMPYLOS_MAX_BAD_POINTS points needed fallback\n"
"    int bad_idx[KAMPYLOS_MAX_BAD_POINTS];\n"
"    int poisoned;             // 1 if any point gave a non-finite/non-positive magnification even\n"
"                               // at the point-source level (degenerate root classification right\n"
"                               // at a critical curve) -- genuinely different from needing\n"
"                               // finite-source fallback, and not something BinaryMagDark fixes\n"
"                               // either; the reference objective() treats this the same way\n"
"                               // (immediate chi2=1e18 for the whole candidate), so this does too.\n"
"                               // Also set (as a repurposed \"dead candidate\" signal) when tE/rho\n"
"                               // were out of fit_binary_local's valid range to begin with.\n"
"};\n"
;

static const char kKampylosClKernelSource[] =
"// Kampylos's batch candidate-evaluation kernel, OpenCL C port of kampylos_gpu_mag.cuh +\n"
"// kampylos_gpu_kernel.cu -- same algorithm (point-source + quadrupole/hexadecapole fast path,\n"
"// per-point fallback reporting, the chi2=S_yy-fs*S_Ay-fb*S_1y closed form), same validated\n"
"// correctness, just OpenCL C instead of CUDA C++ since OpenCL C (based on C99) has no classes,\n"
"// operator overloading, references or templates -- every `kgpu::cx` operator becomes a named\n"
"// function (cx_add, cx_mul, ...), every struct method becomes a free function taking the struct\n"
"// by value or a pointer to it.\n"
"//\n"
"// Requires cl_khr_fp64 (double precision) -- this math was deliberately kept in native double\n"
"// throughout the CUDA version (see that file's own top comment: an earlier, abandoned GPU-port\n"
"// attempt burned a full session chasing FP32 + emulated-double precision bugs in exactly this\n"
"// quintic solver, for no real throughput benefit). Every current discrete desktop GPU this\n"
"// project targets (AMD/Intel/NVIDIA) supports this extension; a device that doesn't gets\n"
"// filtered out by the host-side init code the same way a device with too little GPU RAM already\n"
"// is, not silently given wrong answers.\n"
"#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n"
"\n"
"typedef struct { double re, im; } cx;\n"
"\n"
"inline cx cx_make(double re, double im) { cx z; z.re = re; z.im = im; return z; }\n"
"inline cx cx_add(cx a, cx b) { return cx_make(a.re + b.re, a.im + b.im); }\n"
"inline cx cx_sub(cx a, cx b) { return cx_make(a.re - b.re, a.im - b.im); }\n"
"inline cx cx_mul(cx a, cx b) { return cx_make(a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re); }\n"
"inline cx cx_div(cx a, cx b) {\n"
"    double md = b.re * b.re + b.im * b.im;\n"
"    return cx_make((a.re * b.re + a.im * b.im) / md, (a.im * b.re - a.re * b.im) / md);\n"
"}\n"
"inline cx cx_scale(cx z, double a) { return cx_make(z.re * a, z.im * a); }\n"
"inline cx cx_neg(cx z) { return cx_make(-z.re, -z.im); }\n"
"inline int cx_eq(cx a, cx b) { return a.re == b.re && a.im == b.im; }\n"
"inline double cx_abs2(cx z) { return z.re * z.re + z.im * z.im; }\n"
"inline double cx_abs(cx z) { return sqrt(z.re * z.re + z.im * z.im); }\n"
"inline cx cx_conj(cx z) { return cx_make(z.re, -z.im); }\n"
"inline cx cx_sqrt(cx z) {\n"
"    double md = sqrt(z.re * z.re + z.im * z.im);\n"
"    if (md <= 0) return cx_make(0, 0);\n"
"    return cx_make(sqrt((md + z.re) / 2), sqrt((md - z.re) / 2) * ((z.im > 0) ? 1.0 : -1.0));\n"
"}\n"
"inline cx cx_exp(cx z) {\n"
"    double r = exp(z.re);\n"
"    return cx_make(r * cos(z.im), r * sin(z.im));\n"
"}\n"
"\n"
"#define KAMPYLOS_CL_MAXIT 2000\n"
"\n"
"inline double kgpu_abs2poly(const cx* poly, int degree, cx z) {\n"
"    cx pv = poly[degree];\n"
"    for (int k = degree - 1; k >= 0; k--) pv = cx_add(poly[k], cx_mul(z, pv));\n"
"    return cx_mul(cx_conj(pv), pv).re;\n"
"}\n"
"\n"
"// Plain Laguerre's method for one root -- same simplification as the CUDA version (every root\n"
"// via plain Laguerre with deflation, not the full Laguerre->SG->Newton hybrid\n"
"// cmplx_roots_gen() uses): fewer code paths to get wrong on a port, same guaranteed-ish\n"
"// convergence, see kampylos_gpu_mag.cuh's own comment for the full rationale.\n"
"inline void kgpu_cmplx_laguerre(const cx* poly, int degree, cx* root) {\n"
"    const double FRAC_JUMPS[10] = { 0.64109297, 0.91577881, 0.25921289, 0.50487203,\n"
"        0.08177045, 0.13653241, 0.306162, 0.37794326, 0.04618805, 0.75132137 };\n"
"    const double FRAC_ERR = 2.0e-15;\n"
"    const double two_pi = 6.283185307179586;\n"
"    cx c_one = cx_make(1, 0), zero = cx_make(0, 0);\n"
"\n"
"    double one_nth = 1.0 / degree;\n"
"    double n_1_nth = (degree - 1.0) * one_nth;\n"
"    double two_n_div_n_1 = 2.0 / n_1_nth;\n"
"    cx c_one_nth = cx_make(one_nth, 0.0);\n"
"\n"
"    for (int i = 1; i <= KAMPYLOS_CL_MAXIT; i++) {\n"
"        double ek = cx_abs(poly[degree]);\n"
"        double absroot = cx_abs(*root);\n"
"        cx p = poly[degree], dp = zero, d2p_half = zero;\n"
"        for (int k = degree - 1; k >= 0; k--) {\n"
"            d2p_half = cx_add(dp, cx_mul(d2p_half, *root));\n"
"            dp = cx_add(p, cx_mul(dp, *root));\n"
"            p = cx_add(poly[k], cx_mul(p, *root));\n"
"            ek = absroot * ek + cx_abs(p);\n"
"        }\n"
"\n"
"        double abs2p = cx_mul(cx_conj(p), p).re;\n"
"        if (abs2p == 0) return;\n"
"        double stopping_crit2 = (FRAC_ERR * ek) * (FRAC_ERR * ek);\n"
"        int good_to_go = 0;\n"
"        if (abs2p < stopping_crit2) {\n"
"            if (abs2p < 0.01 * stopping_crit2) return;\n"
"            good_to_go = 1;\n"
"        }\n"
"\n"
"        cx denom = zero, dx;\n"
"        if (!cx_eq(dp, zero)) {\n"
"            cx fac_newton = cx_div(p, dp);\n"
"            cx fac_extra = cx_div(d2p_half, dp);\n"
"            cx F_half = cx_mul(fac_newton, fac_extra);\n"
"            cx denom_sqrt = cx_sqrt(cx_sub(c_one, cx_scale(F_half, two_n_div_n_1)));\n"
"            denom = cx_add(c_one_nth, cx_scale(denom_sqrt, n_1_nth));\n"
"            if (!cx_eq(denom, zero)) dx = cx_div(fac_newton, denom);\n"
"        }\n"
"        if (cx_eq(denom, zero)) {\n"
"            dx = cx_scale(cx_exp(cx_make(0.0, FRAC_JUMPS[i % 10] * two_pi)), absroot + 1.0);\n"
"        }\n"
"\n"
"        cx newroot = cx_sub(*root, dx);\n"
"        if (cx_eq(newroot, *root)) return;\n"
"        if (good_to_go) {\n"
"            if (kgpu_abs2poly(poly, degree, newroot) < abs2p) *root = newroot;\n"
"            return;\n"
"        }\n"
"        if (i % 10 == 0) {\n"
"            double faq = FRAC_JUMPS[(i / 10 - 1) % 10];\n"
"            newroot = cx_sub(*root, cx_scale(dx, faq));\n"
"        }\n"
"        *root = newroot;\n"
"    }\n"
"}\n"
"\n"
"inline void kgpu_cmplx_newton_spec(const cx* poly, int degree, cx* root) {\n"
"    const double FRAC_JUMPS[10] = { 0.64109297, 0.91577881, 0.25921289, 0.50487203,\n"
"        0.08177045, 0.13653241, 0.306162, 0.37794326, 0.04618805, 0.75132137 };\n"
"    const double FRAC_ERR = 2.0e-15;\n"
"    const double two_pi = 6.283185307179586;\n"
"    cx zero = cx_make(0, 0);\n"
"    double stopping_crit2 = 0.0;\n"
"    for (int i = 1; i <= KAMPYLOS_CL_MAXIT; i++) {\n"
"        cx p = poly[degree], dp = zero;\n"
"        if (i % 10 == 1) {\n"
"            double ek = cx_abs(poly[degree]);\n"
"            double absroot = cx_abs(*root);\n"
"            for (int k = degree - 1; k >= 0; k--) {\n"
"                dp = cx_add(p, cx_mul(dp, *root));\n"
"                p = cx_add(poly[k], cx_mul(p, *root));\n"
"                ek = absroot * ek + cx_abs(p);\n"
"            }\n"
"            stopping_crit2 = (FRAC_ERR * ek) * (FRAC_ERR * ek);\n"
"        } else {\n"
"            for (int k = degree - 1; k >= 0; k--) {\n"
"                dp = cx_add(p, cx_mul(dp, *root));\n"
"                p = cx_add(poly[k], cx_mul(p, *root));\n"
"            }\n"
"        }\n"
"        double abs2p = cx_mul(cx_conj(p), p).re;\n"
"        if (abs2p == 0.0) return;\n"
"        int good_to_go = 0;\n"
"        if (abs2p < stopping_crit2) {\n"
"            if (cx_eq(dp, zero)) return;\n"
"            if (abs2p < 0.01 * stopping_crit2) return;\n"
"            good_to_go = 1;\n"
"        }\n"
"        cx dx;\n"
"        if (cx_eq(dp, zero)) {\n"
"            dx = cx_scale(cx_exp(cx_make(0.0, FRAC_JUMPS[i % 10] * two_pi)), cx_abs(*root) + 1.0);\n"
"        } else {\n"
"            dx = cx_div(p, dp);\n"
"        }\n"
"        cx newroot = cx_sub(*root, dx);\n"
"        if (cx_eq(newroot, *root)) return;\n"
"        if (good_to_go) {\n"
"            if (kgpu_abs2poly(poly, degree, newroot) < abs2p) *root = newroot;\n"
"            return;\n"
"        }\n"
"        if (i % 10 == 0) {\n"
"            double faq = FRAC_JUMPS[(i / 10 - 1) % 10];\n"
"            newroot = cx_sub(*root, cx_scale(dx, faq));\n"
"        }\n"
"        *root = newroot;\n"
"    }\n"
"}\n"
"\n"
"inline void kgpu_solve_quadratic_eq(cx* x0, cx* x1, const cx* poly) {\n"
"    cx a = poly[2], b = poly[1], c = poly[0];\n"
"    cx b2 = cx_mul(b, b);\n"
"    cx delta = cx_sqrt(cx_sub(b2, cx_scale(cx_mul(a, c), 4.0)));\n"
"    if (cx_mul(cx_conj(b), delta).re >= 0) *x0 = cx_neg(cx_scale(cx_add(b, delta), 0.5));\n"
"    else *x0 = cx_neg(cx_scale(cx_sub(b, delta), 0.5));\n"
"    if (cx_eq(*x0, cx_make(0, 0))) {\n"
"        *x1 = cx_make(0, 0);\n"
"    } else {\n"
"        *x1 = cx_div(c, *x0);\n"
"        *x0 = cx_div(*x0, a);\n"
"    }\n"
"}\n"
"\n"
"#define KAMPYLOS_CL_MAXDEG 6\n"
"\n"
"inline void kgpu_roots_gen(cx* roots, const cx* poly, int degree) {\n"
"    cx poly2[KAMPYLOS_CL_MAXDEG];\n"
"    for (int j = 0; j <= degree; j++) poly2[j] = poly[j];\n"
"    for (int j = 0; j < degree; j++) roots[j] = cx_make(0, 0);\n"
"\n"
"    for (int n = degree; n >= 3; n--) {\n"
"        kgpu_cmplx_laguerre(poly2, n, &roots[n - 1]);\n"
"        cx coef = poly2[n];\n"
"        for (int i = n - 1; i >= 0; i--) {\n"
"            cx prev = poly2[i];\n"
"            poly2[i] = coef;\n"
"            coef = cx_add(prev, cx_mul(roots[n - 1], coef));\n"
"        }\n"
"    }\n"
"    kgpu_solve_quadratic_eq(&roots[1], &roots[0], poly2);\n"
"\n"
"    for (int n = 0; n < degree; n++) {\n"
"        kgpu_cmplx_newton_spec(poly, degree, &roots[n]);\n"
"    }\n"
"}\n"
"\n"
"typedef struct {\n"
"    double mag;\n"
"    double corrquad;\n"
"    double corrquad2;\n"
"    double safedist;\n"
"    int n_images;\n"
"} BinaryMag0Result;\n"
"\n"
"inline BinaryMag0Result binary_mag0_gpu(double s, double q, double y1v, double y2v) {\n"
"    BinaryMag0Result out;\n"
"    out.mag = -1.0; out.corrquad = 0.0; out.corrquad2 = 0.0; out.safedist = 10.0; out.n_images = 0;\n"
"\n"
"    cx a, qc;\n"
"    if (q < 1.0) { a = cx_make(-s, 0); qc = cx_make(q, 0); }\n"
"    else { a = cx_make(s, 0); qc = cx_make(1.0 / q, 0); }\n"
"    cx m1 = cx_div(cx_make(1, 0), cx_add(cx_make(1, 0), qc));\n"
"    cx m2 = cx_mul(qc, m1);\n"
"\n"
"    cx c20 = a, c21 = m1, c22 = m2;\n"
"    cx c6 = cx_mul(a, a), c7 = cx_mul(c6, a), c8 = cx_mul(m2, m2), c9 = cx_mul(c6, c8);\n"
"    cx c10 = cx_mul(a, m2), c11 = cx_mul(a, m1);\n"
"\n"
"    cx y = cx_make(y1v, y2v);\n"
"    cx yfull = cx_add(y, c11);\n"
"    cx yc = cx_conj(yfull);\n"
"\n"
"    cx c12 = cx_sub(c20, yc);\n"
"    cx c13 = cx_add(c20, yfull);\n"
"    cx c14 = cx_add(c13, yfull);\n"
"    cx c15 = cx_conj(c14);\n"
"    cx c16 = cx_mul(c20, yfull);\n"
"    cx c17 = cx_conj(c16);\n"
"    cx c18 = cx_conj(c12);\n"
"\n"
"    cx poly[6];\n"
"    poly[0] = cx_mul(c9, yfull);\n"
"    poly[1] = cx_add(cx_neg(c9), cx_mul(c10, cx_add(c20, cx_mul(cx_sub(cx_scale(c17, 2.0), cx_add(cx_make(2,0), c6)), yfull))));\n"
"    poly[2] = cx_sub(cx_mul(c10, cx_sub(cx_add(cx_make(1,0), c16), cx_scale(cx_mul(yc, c13), 2.0))), cx_mul(cx_sub(c17, cx_make(1,0)), cx_sub(cx_mul(c16, c12), c18)));\n"
"    poly[3] = cx_sub(cx_add(cx_mul(c10, c15), cx_mul(cx_sub(cx_add(c7, cx_scale(cx_mul(cx_add(cx_make(1,0),c6), yfull), 2.0)), cx_mul(c17, c14)), yc)), cx_mul(c20, c13));\n"
"    poly[4] = cx_sub(cx_neg(c10), cx_mul(c12, cx_sub(cx_mul(yc, cx_add(c13, c20)), cx_make(1,0))));\n"
"    poly[5] = cx_mul(yc, c12);\n"
"\n"
"    cx zr[5];\n"
"    kgpu_roots_gen(zr, poly, 5);\n"
"\n"
"    double good[5];\n"
"    for (int i = 0; i < 5; i++) {\n"
"        cx z = zr[i];\n"
"        cx zc = cx_conj(z);\n"
"        cx ll = cx_add(cx_sub(yfull, z), cx_add(cx_div(c21, cx_sub(zc, c20)), cx_div(c22, zc)));\n"
"        good[i] = cx_abs(ll);\n"
"    }\n"
"    int order[5] = { 0, 1, 2, 3, 4 };\n"
"    for (int i = 0; i < 5; i++)\n"
"        for (int j = i + 1; j < 5; j++)\n"
"            if (good[order[j]] > good[order[i]]) { int t = order[i]; order[i] = order[j]; order[j] = t; }\n"
"    int worst1 = order[0], worst2 = order[1], worst3 = order[2];\n"
"    const double dlmin = 1.0e-4;\n"
"\n"
"    double mag = 0.0;\n"
"    int n_images = 0;\n"
"    int five_roots = !(good[worst2] * dlmin > good[worst3] + 1.e-12);\n"
"    double corrquad = 0.0;\n"
"\n"
"    for (int i = 0; i < 5; i++) {\n"
"        if (!five_roots && (i == worst1 || i == worst2)) continue;\n"
"        cx z = zr[i];\n"
"        cx dza = cx_sub(z, c20);\n"
"        cx za2 = cx_mul(dza, dza);\n"
"        cx zb2 = cx_mul(z, z);\n"
"        cx J1 = cx_add(cx_div(c21, za2), cx_div(c22, zb2));\n"
"        cx J1c = cx_conj(J1);\n"
"        cx dJ = cx_sub(cx_make(1, 0), cx_mul(J1, J1c));\n"
"        cx J2 = cx_neg(cx_scale(cx_add(cx_div(c21, cx_mul(za2, dza)), cx_div(c22, cx_mul(zb2, z))), 2.0));\n"
"\n"
"        double dJre = dJ.re;\n"
"        if (fabs(dJre) < 1.e-9) continue;\n"
"\n"
"        mag += fabs(1.0 / dJre);\n"
"        n_images++;\n"
"\n"
"        cx J3 = cx_scale(cx_add(cx_div(c21, cx_mul(za2, za2)), cx_div(c22, cx_mul(zb2, zb2))), 6.0);\n"
"        double dJ2 = dJre * dJre;\n"
"        cx za2c = cx_mul(J1c, J1c);\n"
"        cx J3s = cx_mul(J3, za2c);\n"
"        double ob2 = (J2.re * J2.re + J2.im * J2.im) * (6.0 - 6.0 * dJre + dJ2);\n"
"        cx J2s = cx_mul(cx_mul(cx_mul(J2, J2), za2c), J1c);\n"
"        double cq = 0.5 * (fabs(ob2 - 6.0 * J2s.re - 2.0 * J3s.re * dJre) + 3.0 * fabs(J2s.im)) / fabs(dJre * dJ2 * dJ2);\n"
"        corrquad += cq;\n"
"    }\n"
"\n"
"    double corrquad2;\n"
"    if (!five_roots) {\n"
"        int idxs[2] = { worst1, worst2 };\n"
"        double cq2 = -2.0;\n"
"        for (int k = 0; k < 2; k++) {\n"
"            int i = idxs[k];\n"
"            cx z = zr[i];\n"
"            cx dza = cx_sub(z, c20);\n"
"            cx za2 = cx_mul(dza, dza);\n"
"            cx zb2 = cx_mul(z, z);\n"
"            cx J1 = cx_add(cx_div(c21, za2), cx_div(c22, zb2));\n"
"            cx J1c = cx_conj(J1);\n"
"            cx dJ = cx_sub(cx_make(1, 0), cx_mul(J1, J1c));\n"
"            cx J2 = cx_neg(cx_scale(cx_add(cx_div(c21, cx_mul(za2, dza)), cx_div(c22, cx_mul(zb2, z))), 2.0));\n"
"\n"
"            cx zaltc = cx_add(yc, cx_add(cx_div(c21, dza), cx_div(c22, z)));\n"
"            cx za2b = cx_sub(zaltc, c20);\n"
"            cx Jaltc = cx_add(cx_div(c21, cx_mul(za2b, za2b)), cx_div(c22, cx_mul(zaltc, zaltc)));\n"
"            cx Jalt = cx_conj(Jaltc);\n"
"            cx JJalt2 = cx_sub(cx_make(1, 0), cx_mul(J1c, Jalt));\n"
"            cx J3 = cx_mul(cx_mul(J2, J1c), JJalt2);\n"
"            J3 = cx_div(cx_sub(J3, cx_mul(cx_conj(J3), Jalt)), cx_scale(cx_mul(JJalt2, JJalt2), dJ.re));\n"
"            double cq = (dJ.re < -10) ? -1.0 : (J3.re * J3.re + J3.im * J3.im);\n"
"            if (k == 0) {\n"
"                cq2 = cq;\n"
"            } else {\n"
"                if (cq2 < 0 || cq < 0) cq2 = 0;\n"
"                else if (cq > cq2) cq2 = cq;\n"
"            }\n"
"        }\n"
"        corrquad2 = cq2;\n"
"    } else {\n"
"        corrquad2 = 0.0;\n"
"    }\n"
"\n"
"    double safedist;\n"
"    if (qc.re < 0.01) {\n"
"        double sd = y1v + (a.re - 1.0 / a.re) * c21.re;\n"
"        safedist = sd * sd + y2v * y2v - 4.0 * sqrt(qc.re) / (a.re * a.re);\n"
"    } else {\n"
"        double sabs = fabs(a.re);\n"
"        double Rinf = sabs + 1.0 / sabs + 2.0;\n"
"        double d2 = y1v * y1v + y2v * y2v;\n"
"        safedist = 10.0;\n"
"        if (d2 > Rinf * Rinf) {\n"
"            double d = sqrt(d2);\n"
"            safedist = (d - Rinf) * (d - Rinf);\n"
"        }\n"
"    }\n"
"\n"
"    out.mag = (n_images > 0) ? mag : -1.0;\n"
"    out.corrquad = corrquad;\n"
"    out.corrquad2 = corrquad2;\n"
"    out.safedist = safedist;\n"
"    out.n_images = n_images;\n"
"    return out;\n"
"}\n"
"\n"
"inline int binary_mag2_fastpath_ok(const BinaryMag0Result* r, double rho, double Tol) {\n"
"    double rho2 = rho * rho;\n"
"    double cq = r->corrquad * 6.0 * (rho2 + 1.e-4 * Tol);\n"
"    double cq2 = r->corrquad2 * 256.0 * (rho2 + 1.e-8);\n"
"    return (cq < Tol) && (cq2 < 1.0) && (r->safedist > 4.0 * rho2);\n"
"}\n"
"\n"
"// ---------------------------------------------------------------------------------------------\n"
"// The actual kernel. Mirrors kampylos_gpu_kernel.cu's kampylos_eval_candidates exactly -- one\n"
"// OpenCL work-GROUP per candidate (matching one CUDA thread-BLOCK per candidate), work-items\n"
"// within the group splitting the light curve's points, local-memory reduction, per-point bad-list\n"
"// instead of a whole-candidate discard.\n"
"//\n"
"// LightCurvePoint/Candidate/CandidateResult come from kampylos_gpu_types.h -- the SAME header the\n"
"// CUDA side and the host-side completion code (kampylos_gpu_complete.h) use, not a separately\n"
"// hand-copied redefinition, so the two backends' struct layouts can never silently drift apart.\n"
"// That header has no C++-only syntax (plain structs, one #define), so it's valid OpenCL C (a C99\n"
"// dialect) as-is; the host code concatenates its text before this file's own when building the\n"
"// OpenCL program (see kampylos_opencl_search.c), the same way it would be #included in C/C++.\n"
"#define KAMPYLOS_CL_MAX_BAD_POINTS KAMPYLOS_MAX_BAD_POINTS\n"
"// kampylos_gpu_types.h declares \"struct LightCurvePoint { ... };\" (plain C99/C++-compatible\n"
"// syntax) -- C++ treats that tag as a usable type name on its own, but strict C99 (what OpenCL C\n"
"// is based on) doesn't, so these typedefs are added locally here rather than changing the shared\n"
"// header (which needs to stay exactly as C++-usable as it already is for the CUDA/host side).\n"
"typedef struct LightCurvePoint LightCurvePoint;\n"
"typedef struct Candidate Candidate;\n"
"typedef struct CandidateResult CandidateResult;\n"
"\n"
"__kernel void kampylos_eval_candidates(\n"
"    __global const LightCurvePoint* data, int n_points,\n"
"    double log_s, double log_q,\n"
"    __global const Candidate* candidates, int n_candidates,\n"
"    __global CandidateResult* results,\n"
"    __local double* sh,             // 7 * local_size doubles\n"
"    __local int* bad_count,         // 1 int\n"
"    __local int* overflow_flag      // 1 int\n"
") {\n"
"    int cand_idx = get_group_id(0);\n"
"    if (cand_idx >= n_candidates) return;\n"
"\n"
"    int lid = get_local_id(0);\n"
"    int lsize = get_local_size(0);\n"
"\n"
"    if (lid == 0) { *bad_count = 0; *overflow_flag = 0; }\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"    Candidate c = candidates[cand_idx];\n"
"    double tE = exp(c.log_tE);\n"
"    double rho = exp(c.log_rho);\n"
"\n"
"    if (tE < 0.01 || tE > 10000.0 || rho < 1e-6 || rho > 1.0) {\n"
"        if (lid == 0) {\n"
"            __global CandidateResult* r = &results[cand_idx];\n"
"            r->S_AA = r->S_A1 = r->S_11 = r->S_Ay = r->S_1y = r->S_yy = 0;\n"
"            r->n_bad = 0; r->overflow = 0; r->poisoned = 1;\n"
"        }\n"
"        return;\n"
"    }\n"
"\n"
"    double s = exp(log_s), q = exp(log_q);\n"
"    double salpha = sin(c.alpha), calpha = cos(c.alpha);\n"
"    double tE_inv = 1.0 / tE;\n"
"\n"
"    double S_AA = 0, S_A1 = 0, S_11 = 0, S_Ay = 0, S_1y = 0, S_yy = 0;\n"
"    double any_invalid = 0;\n"
"\n"
"    for (int i = lid; i < n_points; i += lsize) {\n"
"        double t = data[i].t;\n"
"        double tn = (t - c.t0) * tE_inv;\n"
"        double y1 = c.u0 * salpha - tn * calpha;\n"
"        double y2 = -c.u0 * calpha - tn * salpha;\n"
"\n"
"        BinaryMag0Result r = binary_mag0_gpu(s, q, y1, y2);\n"
"        double A = r.mag;\n"
"        if (!(A > 0) || !isfinite(A)) {\n"
"            any_invalid = 1.0;\n"
"            continue;\n"
"        }\n"
"        if (!binary_mag2_fastpath_ok(&r, rho, 1.e-2)) {\n"
"            int slot = atomic_inc(bad_count);\n"
"            if (slot < KAMPYLOS_CL_MAX_BAD_POINTS) {\n"
"                results[cand_idx].bad_idx[slot] = i;\n"
"            } else {\n"
"                *overflow_flag = 1;\n"
"            }\n"
"            continue;\n"
"        }\n"
"\n"
"        double sigma = data[i].sigma;\n"
"        double w = 1.0 / (sigma * sigma);\n"
"        double flux = data[i].flux;\n"
"        S_AA += w * A * A;\n"
"        S_A1 += w * A;\n"
"        S_11 += w;\n"
"        S_Ay += w * A * flux;\n"
"        S_1y += w * flux;\n"
"        S_yy += w * flux * flux;\n"
"    }\n"
"\n"
"    sh[0 * lsize + lid] = S_AA;\n"
"    sh[1 * lsize + lid] = S_A1;\n"
"    sh[2 * lsize + lid] = S_11;\n"
"    sh[3 * lsize + lid] = S_Ay;\n"
"    sh[4 * lsize + lid] = S_1y;\n"
"    sh[5 * lsize + lid] = S_yy;\n"
"    sh[6 * lsize + lid] = any_invalid;\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"    for (int stride = lsize / 2; stride > 0; stride >>= 1) {\n"
"        if (lid < stride) {\n"
"            for (int k = 0; k < 7; k++) sh[k * lsize + lid] += sh[k * lsize + lid + stride];\n"
"        }\n"
"        barrier(CLK_LOCAL_MEM_FENCE);\n"
"    }\n"
"\n"
"    if (lid == 0) {\n"
"        __global CandidateResult* r = &results[cand_idx];\n"
"        if (sh[6 * lsize] > 0) {\n"
"            r->S_AA = r->S_A1 = r->S_11 = r->S_Ay = r->S_1y = r->S_yy = 0;\n"
"            r->n_bad = 0; r->overflow = 0; r->poisoned = 1;\n"
"        } else {\n"
"            r->S_AA = sh[0 * lsize]; r->S_A1 = sh[1 * lsize]; r->S_11 = sh[2 * lsize];\n"
"            r->S_Ay = sh[3 * lsize]; r->S_1y = sh[4 * lsize]; r->S_yy = sh[5 * lsize];\n"
"            r->n_bad = min(*bad_count, (int)KAMPYLOS_CL_MAX_BAD_POINTS);\n"
"            r->overflow = *overflow_flag;\n"
"            r->poisoned = 0;\n"
"        }\n"
"    }\n"
"}\n"
;

